### ISSUE TITLE
RC3 is getting stuck parsing one of my files

### ISSUE THREAD

**Issue by mhoskinson7** [arlinsandbulte/Pro7-Media-Sweeper#9] opened 2022-01-20 01:56 UTC
Every other version I have tried of the media sweeper works fine. On v2.0-RC3, the program gets stuck when it says it is parsing my file Baptism.pro. I tried deleting that file, and then it got stuck on Blessed Assurance.pro. Deleted both and then it got stuck on Death Was Arrested.pro. Deleted all those and then it got stuck on Forever.pro. It never goes to actually moving the files to the Pro7 Media Sweeper folder.

[Here is a link to a folder with those files that it gets stuck on if you want to give it a try.](https://gracechurchdsm-my.sharepoint.com/:f:/g/personal/mhoskinson_gracehome_com/Euftid_jheRDpVpGKzkJ5esBK39lwCP3GR5Qyh4xFfXsRA?e=t6Wy9G)

Please let me know if there is anything else I should try! Thanks for making this program!

These are the log files when I was testing it out with it getting stuck.

[Sweep_Log (20220119-194827).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/7901665/Sweep_Log.20220119-194827.log)
[Sweep_Log (20220119-194930).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/7901666/Sweep_Log.20220119-194930.log)
[Sweep_Log (20220119-194952).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/7901667/Sweep_Log.20220119-194952.log)
[Sweep_Log (20220119-195035).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/7901668/Sweep_Log.20220119-195035.log)

**Comment by arlinsandbulte** [comment] 2022-01-20 04:16
Thanks for the report, @mhoskinson7 
I've replicated your issue and will work on a fix.  

The issue is due to the name of one of your media files: 
`C:\\Users\\Worship\\Documents\\ProPresenter\\Media\\Assets\\41286.jpg` (there may be others).
The sequence of `\412` in the file name path is getting mis-interpreted as a special character in my code.  

That's because I added code to account for special characters such as 'ñ' & 'ñ'.  
Behind the scenes, those special characters get encoded as escaped sequences of 3 octal digits, i.e.: \123
So, I need to figure out a way to differentiate those special character sequences from a normal sequence of \412...

**Comment by arlinsandbulte** [comment] 2022-01-20 07:00
I think i got this issue fixed.  The fix is ugly, but it works... I think.
I'll be releasing v2.0-RC4 soon so you can verify.
THANKS so much for the good error report.  Your sample files and logs helped A LOT!

**Comment by arlinsandbulte** [comment] 2022-01-20 07:48
v2.0-RC4 is released.
I'm going to close this issue.  Feel free to reopen if this issue is not closed.
If you find any other issues, please open a new issue.
https://github.com/arlinsandbulte/Pro7-Media-Sweeper/releases/tag/v2.0-RC4

**Closed by arlinsandbulte** 2022-01-20 07:48 UTC
